### ISSUE TITLE
Website doesn't work on Firefox

### ISSUE THREAD

**Issue by Ev1lbl0w** [afonsomatos/tm-site#2]
Opening https://www.afonso.app/tm-site/ just shows a blank screen on Firefox 74.0. Works on Chromium though.

Console shows this: 
![image](https://user-images.githubusercontent.com/6501975/76632704-8a8a0b80-653b-11ea-8615-acb910273bea.png)

**Comment by afonsomatos** [comment]
Thanks, I've just fixed it.
Firefox doesn't support named regex groups.
